# Project information
site_name: ShellHub
site_description: 'ShellHub enables teams to easily access any Linux device behind firewall and NAT'
site_url: 'https://github.com/shellhub-io'

# Repository
repo_name: 'shellhub-io/shellhub'
repo_url: 'https://github.com/shellhub-io/shellhub'

# Deployment
remote_branch: master

# Copyright
copyright: 'Copyright &copy; 2020 O.S. Systems'

# Configuration
edit_uri: '/shellhub-io/shellhub-io.github.io/edit/src/docs'

# Theme
theme:
  name: 'material'
  features:
    - tabs
  logo: img/logo-inverted.png

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/OSSystems'
    - type: 'twitter'
      link: 'https://twitter.com/OSSystemsNews?s=20'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/ossystems'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        'getting-started.md': 'installing.md'
  - markdownextradata: {}

# Navigation
nav:
  - Introduction: index.md
  - How it Works: introduction.md
  - Features: features.md
  - Getting started:
    - Installing: getting-started/installing.md
    - Creating account: getting-started/creating-account.md
    - Registering a device: getting-started/registering-device.md
    - Connecting to a device: getting-started/connecting-device.md
  - ShellHub Cloud:
    - Firewall Rules: cloud/managing-firewall-rules.md
  - Troubleshooting:
      Frequently Encountered Issues: troubleshooting.md
# Extra data
extra:
  shellhub:
    latest_version: v0.3.6
